### ISSUE TITLE
It's not working to access more than 3 months of historical data

### ISSUE THREAD

**Issue by gbgmian** [sentimentinvestor/sentipy#1]
I just signed up for paid plan at sentimentinvestor.com, trying to get some historical data with sentipy but I only get data returned since april. Also tried to download dataset from dashboard but nothing happens at all after clicking "Next" (tried "XLE/2017" and "AMC/2021"). Is this the right place to get help? If not, where do I get support for the service?

**Comment by zeevox** [comment]
I believe that this isn't the best place to ask for help, as SentiPy is just a wrapper and does not provide any functionality of its own. I would suggest emailing the Sentiment Investor support line at hello@sentimentinvestor.com, since this seems to be an issue with the data itself.
