### ISSUE TITLE
Sudden error with sentipy.sort

### ISSUE THREAD

**Issue by menkesu** [sentimentinvestor/sentipy#10]
Hi,
I've been using sentipy for months with no issue. past days the issue started - my code is:
token= "XXXXX"
key= "YYYY"
sentipy = Sentipy(token=token, key=key)
metric = "AHI"
limit = 100

sortData = sentipy.sort(limit, metric)

and I get an error:
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-51-7ce5e29a7326> in <module>
     31 # The results of the query can be accessed through the SortData object. This contains a sort field, which is an array of BasicTicker objects. The fields these contain are listed below.
     32 
---> 33 sortData = sentipy.sort(limit, metric)
     34 sortData

/usr/local/anaconda3/lib/python3.8/site-packages/sentipy/sentipy.py in sort(self, metric, limit)
     35     }
     36     response = self.base_request("sort", params=params)
---> 37     return SortData(response)
     38 
     39   def historical(self, symbol, metric):

/usr/local/anaconda3/lib/python3.8/site-packages/sentipy/sentipy.py in __init__(self, json)
     86 class SortData():
     87   def __init__(self, json):
---> 88     self.sort = [BasicTicker(dp) for dp in json]
     89 
     90 

/usr/local/anaconda3/lib/python3.8/site-packages/sentipy/sentipy.py in <listcomp>(.0)
     86 class SortData():
     87   def __init__(self, json):
---> 88     self.sort = [BasicTicker(dp) for dp in json]
     89 
     90 

/usr/local/anaconda3/lib/python3.8/site-packages/sentipy/sentipy.py in __init__(self, json)
     47 class BasicTicker():
     48   def __init__(self, json):
---> 49     self.ticker = json.get("ticker")
     50     self.AHI = json.get("AHI")
     51     self.sentiment = json.get("sentiment")

AttributeError: 'str' object has no attribute 'get'`

**Comment by zeevox** [comment]
Hi there,

I think this is an issue with the API. I get the following error when
accessing the HTTP API through my browser:

```
Error: could not handle the request
```

So I do not think that this is an issue with `sentipy`. If the API is still
down, email hello@sentimentinvestor.com directly please.

All the best
